### ISSUE TITLE
Issue with big p parameter

### ISSUE THREAD

**Issue by homakov** [Crypho/cordova-plugin-scrypt#8]
Some derivation results for p=10 N=2^18 on a Galaxy S8:

21.820 21.933 seconds with plugins.scrypt 

23.577 22.672 with scrypt-async-js (nice job @dchest) 

I will do more tests yet... it's weird that a native lib is barely faster than a pure JS lib. I was wondering is there anything on top of your head that can be optimized to deal with `p` more smoothly, like run derivation in parallel?

This is cross platform code used:

```

function derive(password, email, cb){
  var opts = {
    N: Math.pow(2,18),
    interruptStep: 0,
    p: 10,
    r: 8,
    dkLen: 32,
    encoding: 'base64'
  }

  if(E){
    nodeRequire("scrypt").hash(password,opts,32,email).then(function(root){cb(root.toString("base64"))})
  }else if(window.plugins && window.plugins.scrypt){
    window.plugins.scrypt(function(root){cb(hexToBase64(root));}, alert, password, email, opts)
  }else{
    setTimeout(function(){ //interrupt step prevents animation
      scryptjs(password, email, opts, cb)
    },0)
  }
}
```

**Comment by ggozad** [comment]
At the time we did the plugin the only implementation was the one in sjcl which has abysmal performance. I doubt we are going to pursue optimising this further as we merely used the reference implementation and made it compile on the various platforms + bindings. That said, feel free to make a PR :)

**Comment by ggozad** [comment]
Still it is surprising you get such a small difference. I bet this is on android? on iOS you are going to get a lot more. 
I do not think one can optimize a lot further due to the nature of scrypt too.

**Comment by dchest** [comment]
Looks like [crypto_scrypt-**nosse**.c](https://github.com/Crypho/cordova-plugin-scrypt/blob/master/src/libscrypt/crypto_scrypt-nosse.c) is actually [crypto_scrypt-**ref**.c](https://github.com/Tarsnap/scrypt/blob/1.1.6/lib/crypto/crypto_scrypt-ref.c), which is a slow reference implementation using 8-bit arrays. scrypt-async-js and the proper [-nosse](https://github.com/Tarsnap/scrypt/blob/1.1.6/lib/crypto/crypto_scrypt-nosse.c) version use 32-bit arrays. I think you can replace it (with [this](https://github.com/Tarsnap/scrypt/blob/1.1.6/lib/crypto/crypto_scrypt-nosse.c)), tweak to what cordova-plugin-scrypt/src/libscrypt/ expects and it will be much faster.

**Comment by homakov** [comment]
I just run tests on ios emulator and on a real device: results are strange. On emulator scrypt plugin is much slower than scrypt js. On a real device it is a bit faster but both are painfully slow, like 120 seconds for N=2^16 p=3. Is it normal? What params do you use for your projects by the way?

**Comment by dchest** [comment]
@homakov no, it's not normal. 3 sec in Chrome on Android (Snapdragon 650). Try [this in Safari](http://dchest.github.io/scrypt-async-js/). The reason for JS slowness may be the absence of JIT compilation (I don't know about Cordova, but React Native, for example, doesn't have it due to the use of JavaScriptCore — only WKWebView has it), but I'm baffled about slow native performance. Could it be that it's an unoptimized/debug built?

**Comment by homakov** [comment]
Ok, when you run with --release mode it is actually faster. Now for 2^18 p=10 on my macbook it takes 8 seconds while on ipad ~32. I guess  compiler optimizes plugin. 

Btw what about these warnings:

```
[329:40605] THREAD WARNING: ['ScryptPlugin'] took '1457.798828' ms. Plugin should use a background thread.
```

**Comment by ggozad** [comment]
You should benchmark on real devices. And yes ``--release`` is important there :)
The warning is what it says. It would be better (and not too hard if you want to give it a try) to run this on a thread instead.

**Comment by homakov** [comment]
How to run in a thread? Online search tells me I'd need to change some native code. Will it make script faster? because I don't mind blocking the UI

**Comment by ggozad** [comment]
Yes this would need to be done on the plugin level through ``runInBackground`` on iOS and ``cordova.getThreadPool`` on android iirc.

**Comment by homakov** [comment]
@ggozad I've figured out I don't need to runInBackground because the speed is the same. 

Side question: have you looked into integrating other cordova platforms such as UWP and osx? Or is it a lot of extra coding?

**Comment by ggozad** [comment]
Hey @homakov. I haven't looked at osx or windows. I would imagine osx must be very straightforward, probably the iOS thing will do just fine. Windows on the other hand might be a world of pain.

**Comment by ggozad** [comment]
With regards to background it's worthwhile if you wanna do it and I would be happy to accept it. It would not of course change the speed, but it would free up the main thread for UI. Let me know if I can close this, we can take background seperately.

**Comment by homakov** [comment]
Got it.
So, in the end big p is not so slow if compiled in --release mode and compiler optimization to Fastest. Closing it.
